### ISSUE TITLE
What is the best way to include a PDO database class?

### ISSUE THREAD

**Issue by Silvester20** [panique/mini3#11]
Like the title says, I've got a database class with a lot of database functions in it like connecting, updating, inserting, get last inserted id etc.

Right now in mini3 the PDO database connection is made inside the core Model.php but because I need those database class for more applications I want to include a external database class.

So I was wondering what the best method is for this 'framework' how to include a Database.php class according to the mini3 namespaces?

**Comment by jimgwhit** [comment]
Work it in application/Core/Model.php
