### ISSUE TITLE
Suggestion: do not redirect to /error, but just show a nice 404 error page on the current URL

### ISSUE THREAD

**Issue by JelmerD** [panique/mini3#13]
You don't want to redirect to another URL if you expect a 404. There is no 404 response code and it's not very common to redirect.

Normal behavior: just show a 404 page on the current URL.

My suggestion:

Change https://github.com/panique/mini3/blob/master/application/Core/Application.php#L55 and https://github.com/panique/mini3/blob/master/application/Core/Application.php#L59 to:

```php
$this->url_controller = new \Mini\Controller\ErrorController();
$this->url_controller->notFound();
```

And change https://github.com/panique/mini3/blob/master/application/Controller/ErrorController.php#L20 to `notFound`.

Then I will be able to set a customised error page for a 404. Direct access to `/error` should be blocked.

**Comment by JaoNoctus** [comment]
@JelmerD I liked the suggestion. Can you send us a PR?

**Comment by JaoNoctus** [comment]
@panique What do you think about it?

**Comment by panique** [comment]
This is perfect :) I'm currently in stress with my job, but when there'S time i'll definitly add this to the project. Big thanks @JelmerD and @JaoNoctus !
