### ISSUE TITLE
How to integrate a login system?

### ISSUE THREAD

**Issue by JhonatanPereira** [panique/mini3#14]
What is the best way to integrate a login system in MINI3?
Implementing login check and permission check on a Base Controller class that execute db querys using a User model?

**Comment by panique** [comment]
Thats a BIG topic and you'll need a lot of work for this, for i can only recommend you to use a modern framework that has user authentication on board or try out HUGE, it's another project i've built some time ago, does exactly what you need, but might be oversized. It's also not developed anymore...

https://github.com/panique/huge

**Comment by JhonatanPereira** [comment]
Thanks for the advice and I have to say that your work is awesome. I merged mini3 with HUGE and did some modifications, it's working fine

**Comment by Portekoi** [comment]
@JhonatanPereira Do you have a repo with this merge between MINI3 and Huge?

**Comment by panique** [comment]
Yeah that repo would be really interesting!

**Comment by lmgnns** [comment]
I'm waiting with entusiasm
