### ISSUE TITLE
 Helper::debug is given error 

### ISSUE THREAD

**Issue by uniqueanurag** [panique/mini3#16]
Hi,

I'm getting error below, please check out... and teach me 

Fatal error: Uncaught Error: Class 'master\Model\Helper' not found in C:\xampp\htdocs\master\application\Model\User.php:17 Stack trace: #0 C:\xampp\htdocs\master\application\Controller\UserController.php(17): master\Model\User->register('anurag', 'Sinha', 'dev.sinha14@gma...', 's', '1231231231', '9891289891', '9891289891 9891...', 'anurag', 'female', '9891289891', '110092') #1 C:\xampp\htdocs\master\application\Core\Application.php(47): master\Controller\UserController->register() #2 C:\xampp\htdocs\master\public\index.php(37): master\Core\Application->__construct() #3 {main} thrown in C:\xampp\htdocs\master\application\Model\User.php on line 17

When i want to print debug

// useful for debugging: you can see the SQL behind above construction by using:
echo '[ PDO DEBUG ]: ' . Helper::debugPDO($sql, $parameters);  exit();

Regards
Anurag

**Comment by panique** [comment]
Please follow the install tutorial or use the auto-installer!

**Comment by sousaworld** [comment]
Hi @uniqueanurag ,

I think it's a problem with namespaces...
for the  song example I had to add
 `use Mini\Libs as L` 

and then change the debug echo call to 
 `echo '[ PDO DEBUG ]: ' . L\Helper::debugPDO($sql, $parameters);  exit();`

to get  the helper to work

**Comment by sousaworld** [comment]
actually you can call it like this:

`echo '[ PDO DEBUG ]: ' . \Mini\Libs\Helper::debugPDO($sql, $parameters); exit();`

remember to check Libs folder name ( vs libs )

**Comment by themancalledjakob** [comment]
hmmm somehow both these fixes don't work for me

**Comment by panique** [comment]
Hey, it's fixed now :)
