### ISSUE TITLE
Class 'Mini\Core\Application not found 

### ISSUE THREAD

**Issue by eldinor** [panique/mini3#17]
Dear friends,

Thank you very much for Mini, it helps a lot for the beginners.
I was going to try Mini3, but have got only errors :(

On php 5.6:
Fatal error: Class 'Mini\Core\Application' not found in .../.../mini3-master/public/index.php on line 37

On php 7.0: 
Uncaught Error:  Stack trace: #0 {main} thrown in  .../.../mini3-master/public/index.php on line 37

**Comment by panique** [comment]
Thanks! It's not really possible to help you without any infirmation about what exactly you are doing! There is a bulletproof self-installer, a vagrant installer and even a tutorial for manual installation, so where exactly does it break ?

**Comment by eldinor** [comment]
Thank you for the answer!
Seems that the problem relates to my composer settings.
I'll let you know when I'll solve it.

**Comment by eldinor** [comment]
Problem solved with using another version of webserver for Windows.
Everything is OK now, thank you for the attention.

**Comment by abelardolg** [comment]
Hi.
I am having the same issue: 
Fatal error: Uncaught Error: Class 'Mini\Core\Application' not found in /lab/mini3/public/index.php:37 Stack trace: #0 {main} thrown in lab/mini3/public/index.php on line 37

I didn't modify any file.

Could be a matter related to mod_rewrite directive?

From now, thanks!
