### ISSUE TITLE
Really a good example, Do you have any version with routers

### ISSUE THREAD

**Issue by ranapartap** [panique/mini3#22]
Hi 

First of all thanks for creating beautiful app. Really a good example to kick start for a basic core php application. I always like to code in core due to small size and keep only required code pieces. 

You have user namespaces in a very good manner I always stuck with them. 

Can you please use some router library like klein [https://github.com/klein/klein.php](https://github.com/klein/klein.php) . I have used it and is a good library.

I have a problem with the app I have started php server in the root directory. App is working fine but routing is not working. urls are updating in the address bar but content remains the same.

Please try to use any router that will be very good practice. Also Klein router has built in template renderer to use partials layouts and yield content etc. 

I know we always love our child. Its really great, but there is always the scope of improvements.

Thank you in advance.
Rana

**Comment by panique** [comment]
Hello Rana, please use the official installer script or have a look into the apache / nginx configs and everything will run fine!
