### ISSUE TITLE
[TODO] Helper lib doesn't work as folder/file needs to be uppercase name

### ISSUE THREAD

**Issue by SkyNeT-ProD** [panique/mini3#23]
I changed the name of the folder libs to Libs to make it load. I have the correct namespace is my helper.php : namespace Mini\Libs and I call it like this : \Mini\Libs\Helper::debugPDO() (I know I need the params but that's not the problem).
Error : Fatal error: Uncaught Error: Class 'Mini\Libs\Helper' not found in

**Comment by SkyNeT-ProD** [comment]
Solution : After reading the PSR-4 standards we also need to make the first letter of the PHP file an uppercase.

**Comment by panique** [comment]
@SkyNeT-ProD Thanks for the report, can you please say which operating system your installation is running on ? And in case you are a Vagrant box, what's the host operating system ?

**Comment by SkyNeT-ProD** [comment]
@panique Ubuntu 17, using lampp, I don't use Vagrant.

**Comment by panique** [comment]
it is fixed now :)
