### ISSUE TITLE
URLs with dash

### ISSUE THREAD

**Issue by johoehn** [panique/mini3#30]
Hi, is it possible, to create urls like /home/edit-song?

**Comment by hozzaq** [comment]
it's possible but you have to modify application.php for it to work because function name can't use dash, you have to replace it with underscore or remove it before calling the action 

cmiiw

**Comment by johoehn** [comment]
But then you get duplicate content with /home/edit_song, right? So you have to disable urls with _ globally and redirect them to /error.

**Comment by mhco** [comment]
I know this is closed, but just for future reference, it can be done with a single line inserted into [Application.php at line 33](https://github.com/panique/mini3/blob/b58aef019b6f052fd8c45723c534268b540c863a/application/Core/Application.php#L33):

```
if (strpos($this->url_action, '-') > 0) $this->url_action = lcfirst(str_replace(' ', '', ucwords(str_replace('-', ' ', $this->url_action))));
```

Note: I'm not saying this is a foolproof solution, nor am I even saying it's a good idea at all (I haven't really thought of the consequences), but this leaves your methods with camelcase names, and only really affects URLs that have dashes in them. It's still up to you to ensure that this works perfectly with your site. You'll need to test it out fully before you use it in production.
