### ISSUE TITLE
How to load an inner html included into a php file

### ISSUE THREAD

**Issue by abelardolg** [panique/mini3#34]
Hi everyone,

When HomeController is called, is executed three "require" statements:
```
require APP . 'view/_templates/header.php';
        require APP . 'view/index.php';
        require APP . 'view/_templates/footer.php';
```

Inside the 'view/index.php' file, there is this statement:
`<div w3-include-html="http:<?php echo URL; ?>Mini/view/landpage/formSuscripcion.html"></div>`

The 'w3-include-html' tag works -> more reference at: https://www.w3schools.com/howto/howto_html_include.asp

When MIni3 loads this line, shows an error. How could I load that 'formSuscripcion.html' file?

Let me know if you have encountered my issue.

Any help would be welcome.

Best regards.

**Comment by abelardolg** [comment]
I put this line:
<div w3-include-html="http:<?php echo URL; ?>Mini/view/landpage/formSuscripcion.html"></div>

Is right?
Best regards.

**Comment by abelardolg** [comment]
This is the message showed from ErrorController:
This is the Error-page. Will be shown when a page (= controller / method) does not exist.

I understand that this error is generated because at the line:
`<div w3-include-html="http:<?php echo URL; ?>Mini/view/landpage/formSuscripcion.html"></div>`. This should be called by another way to load this html but I don't know which one.

Any help?

Best regards.

**Comment by panique** [comment]
Sorry i have absolutly no idea what you want to say

**Comment by panique** [comment]
Are you sure you have read the readme ? This is a little framework and it's not about including HTML files, maybe you look at the documentation again, it will probably solve your problem

**Comment by abelardolg** [comment]
Hi @panique 
I have read the documentation and it works fine your framework but when I want to include this inner html it doesn't work: cause that error message.

How would I write that line to load that html?

Best regards.
