### ISSUE TITLE
Generating PDFs with PHP mini

### ISSUE THREAD

**Issue by johoehn** [panique/mini3#51]
I want to use dompdf, I installed it via composer. 
I did 

use Dompdf\Dompdf;

in top of the Controller and used it like the example says: 

        $dompdf = new Dompdf();
        $dompdf->loadHtml('hello world');
        $dompdf->setPaper('A4', 'landscape');
        $dompdf->render();
        $dompdf->stream();

The browser cannot open the pdf, the error occurs only in PHP Mini framework, I tried it in a separate project and it worked without problems. Do you have any ideas?

**Comment by panique** [comment]
Hi, do you have some kind of error message ?

**Comment by LearningTools** [comment]
Hello, I just did a test with the FPDF library and if you generate the pdf, you should try this other library, greetings.
**sorry for my bad English**
