### ISSUE TITLE
How to share function across all views

### ISSUE THREAD

**Issue by hollow6** [panique/mini3#69]
I'm just getting into using Mini3 MVC framework but am struggling with the concept of where to code a function that is to be used by ALL views. Can anyone help me? Thanks in advance

**Comment by ebitkov** [comment]
That's probably a question for yourself and how you want to structure your code.

You probably could create a function under the `view` folder - for example `globals`, and create functions there, like:

```php
<?php 
// file: application/view/globals/do_something.php

namespace Mini\view\globals;

do_something() { ... }
```

And in your view-files you could use your function like this: `Mini\view\globals\do_something();`

But you could put the function basically anywhere in the `application` folder. 

There is not really a 'right' or 'wrong' predefined by Mini3 here.

**Comment by hollow6** [comment]
> That's probably a question for yourself and how you want to structure your code.
> 
> You probably could create a function under the `view` folder - for example `globals`, and create functions there, like:
> 
> ```
> <?php 
> // file: application/view/globals/do_something.php
> 
> namespace Mini\view\globals;
> 
> do_something() { ... }
> ```
> 
> And in your view-files you could use your function like this: `Mini\view\globals\do_something();`
> 
> But you could put the function basically anywhere in the `application` folder.
> 
> There is not really a 'right' or 'wrong' predefined by Mini3 here.

I will do that. Thank you for your guidance

**Comment by crystlbrd** [comment]
@hollow6 @panique can we close this one?

**Comment by hollow6** [comment]
> @hollow6 @panique can we close this one?

Yes thanks
