### ISSUE TITLE
Pull 61 wasn't applied to the develop branch. 

### ISSUE THREAD

**Issue by BeardyMike** [panique/mini3#70]
https://github.com/panique/mini3/pull/61

This pull was applied to the MASTER branch, but not the DEVELOP branch.

The pull is a fantastic feature, and it makes sense that the DEVELOP branch should have it as well. 

If there's something I'm missing, please let me know as I can't figure out why it wasn't applied to both....

**Comment by BeardyMike** [comment]
I've made pull request with the changes. That feels like a better place to give objections, and hash out reasoning.

**Comment by panique** [comment]
hey @BeardyMike , thanks for your eye for the detail, nice one! I just checked and it seems that over the years several changes have been made to different branches of the projects, but not in sync, so we now have some problems (see the screenshots below please). Also, the tutorial and the README have not been updated in some cases.

Right now i'm too busy to do this, I i would say: let's keep this on hold, I'll check back later ;)

<img width="486" alt="Bildschirmfoto 2024-02-20 um 22 02 48" src="https://github.com/panique/mini3/assets/156321/79ad2aee-900e-4d9d-b448-9e67eb6481a4">


<img width="587" alt="Bildschirmfoto 2024-02-20 um 22 02 40" src="https://github.com/panique/mini3/assets/156321/ae2e3030-35aa-415f-91c7-77855eda42a6">
