### ISSUE TITLE
Cleanup some issues

### ISSUE THREAD

**Issue by crystlbrd** [panique/mini3#72]
Hey,

I started to review some of the issues here and found that many of the still open ones could actually be closed. Here a list:

- https://github.com/panique/mini3/issues/69
- https://github.com/panique/mini3/issues/68
- https://github.com/panique/mini3/issues/58
- https://github.com/panique/mini3/issues/56
- https://github.com/panique/mini3/issues/51
- https://github.com/panique/mini3/issues/50
- https://github.com/panique/mini3/issues/35

@panique how do you feel about closing them?

**Comment by panique** [comment]
Thank you so much, all closed now! sorry for long delay, I'm not really "working here anymore" ;)
